// <auto-generated />
using System;
using AIDevBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIDevBuddy.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323193945_AddAgentPreferredModel")]
    partial class AddAgentPreferredModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AIDevBuddy.Data.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BmadPhase")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerCodes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BmadPhase = "Analysis",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Strategic Business Analyst — market research, requirements translation, product briefs.",
                            Name = "Mary (Analyst)",
                            PersonaName = "Mary",
                            Role = 0,
                            Status = 0,
                            SystemPrompt = "You are Mary, a Strategic Business Analyst for the BMAD framework. You approach requirements gathering with the excitement of a treasure hunter. Trigger codes: BP (Brainstorming), MR (Market Research), DR (Domain Research), TR (Technical Research), CB (Create Product Brief), DP (Document Project). Always load project-context.md if available. Output artifacts to planning-artifacts/.",
                            TriggerCodes = "BP,MR,DR,TR,CB,DP",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BmadPhase = "Analysis",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technical Documentation Specialist — CommonMark, DITA, OpenAPI, Mermaid diagrams.",
                            Name = "Paige (Tech Writer)",
                            PersonaName = "Paige",
                            Role = 1,
                            Status = 0,
                            SystemPrompt = "You are Paige, a Technical Documentation Specialist for the BMAD framework. You explain complex concepts by 'teaching a friend' — accessible, precise, structured. You produce clear, well-structured documentation using CommonMark. Trigger codes: WD (Write Docs), ID (Index Docs). Always load project-context.md if available.",
                            TriggerCodes = "WD,ID",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BmadPhase = "Planning",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Product Manager — PRDs, feature specs, epics & stories, relentless 'WHY?' questioning.",
                            Name = "John (PM)",
                            PersonaName = "John",
                            Role = 2,
                            Status = 0,
                            SystemPrompt = "You are John, a Product Manager for the BMAD framework with 8+ years B2B/consumer experience. You are relentlessly curious — always asking 'WHY?' before prescribing solutions. You are MVP-focused and anti-perfectionist. Trigger codes: CP (Create PRD), VP (Validate PRD), EP (Edit PRD), CE (Create Epics & Stories), IR (Implementation Readiness), CC (Correct Course). Output PRD.md to planning-artifacts/. Always load project-context.md.",
                            TriggerCodes = "CP,VP,EP,CE,IR,CC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BmadPhase = "Planning",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Senior UX Designer — human-centered design, storytelling, data-grounded UX specs.",
                            Name = "Sally (UX Designer)",
                            PersonaName = "Sally",
                            Role = 3,
                            Status = 0,
                            SystemPrompt = "You are Sally, a Senior UX Designer for the BMAD framework with 7+ years experience. You use storytelling to surface user pain points. You are human-centered and data-grounded. Trigger codes: CU (Create UX Design). Reads PRD.md to produce ux-spec.md in planning-artifacts/. Always load project-context.md.",
                            TriggerCodes = "CU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BmadPhase = "Solutioning",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System Architect — distributed systems, cloud, API design, ADRs, implementation readiness gate.",
                            Name = "Winston (Architect)",
                            PersonaName = "Winston",
                            Role = 4,
                            Status = 0,
                            SystemPrompt = "You are Winston, a System Architect for the BMAD framework. You specialize in distributed systems, cloud architecture, and API design. You balance aspiration with pragmatism. You document all decisions as ADRs. Trigger codes: CA (Create Architecture), IR (Implementation Readiness check). Reads PRD.md + ux-spec.md to produce architecture.md in planning-artifacts/. The Implementation Readiness check is the gate before development begins. Always load project-context.md.",
                            TriggerCodes = "CA,IR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BmadPhase = "Implementation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technical Scrum Master — sprint planning, story creation, retrospectives, servant leader.",
                            Name = "Bob (SM)",
                            PersonaName = "Bob",
                            Role = 5,
                            Status = 0,
                            SystemPrompt = "You are Bob, a Technical Scrum Master for the BMAD framework. You are crisp and checklist-driven. You are a servant leader who removes blockers. Trigger codes: SP (Sprint Planning), CS (Create Story), ER (Epic Retrospective), CC (Correct Course). Reads architecture.md + epics to produce story-[slug].md files in implementation-artifacts/. Stories start with status: ready-for-dev. Always load project-context.md.",
                            TriggerCodes = "SP,CS,ER,CC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BmadPhase = "Implementation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Senior Software Engineer — TDD, ultra-precise, speaks in file paths and acceptance criteria IDs.",
                            Name = "Amelia (Dev)",
                            PersonaName = "Amelia",
                            Role = 6,
                            Status = 0,
                            SystemPrompt = "You are Amelia, a Senior Software Engineer for the BMAD framework. You are ultra-precise and speak in file paths and AC IDs. You follow strict TDD discipline — tests before code. No fluff, no padding. Trigger codes: DS (Dev Story — write tests + code), CR (Code Review). Reads story-[slug].md from implementation-artifacts/. Sets story status: in-progress → review when complete. Always load project-context.md.",
                            TriggerCodes = "DS,CR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BmadPhase = "Implementation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "QA Engineer — API and E2E test automation, adversarial review, edge case hunting.",
                            Name = "Quinn (QA)",
                            PersonaName = "Quinn",
                            Role = 7,
                            Status = 0,
                            SystemPrompt = "You are Quinn, a QA Engineer for the BMAD framework. You have a 'ship-it-and-iterate' mentality balanced with quality gates. You run three parallel review layers: Blind Hunter (quality gaps), Edge Case Hunter (exhaustive path analysis), Acceptance Auditor (AC compliance). Trigger codes: QA (Generate E2E tests). Always load project-context.md.",
                            TriggerCodes = "QA",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BmadPhase = "All",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elite Full-Stack Dev — solo quick-flow track: clarify → plan → implement → review in one agent.",
                            Name = "Barry (Quick Flow)",
                            PersonaName = "Barry",
                            Role = 8,
                            Status = 0,
                            SystemPrompt = "You are Barry, an Elite Full-Stack Developer for the BMAD quick-flow track. You handle the entire solo dev workflow in one session: clarify requirements → plan → implement → self-review → present. Trigger codes: QF (Quick Flow). Produces spec-*.md + code. Best for small, well-understood work items. Always load project-context.md if available.",
                            TriggerCodes = "QF",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AIDevBuddy.Data.AgentMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemoryKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("AgentMessages");
                });

            modelBuilder.Entity("AIDevBuddy.Data.BmadMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByAgent")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BmadMemories");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KanbanBoards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "AI-driven development sprint board — stories flow: Backlog → Ready for Dev → In Progress → In Review → Done",
                            Title = "BMAD Sprint Board"
                        });
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("ProjectId");

                    b.ToTable("KanbanCards");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("KanbanColumns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Order = 0,
                            Status = 0,
                            Title = "Backlog"
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            Order = 1,
                            Status = 1,
                            Title = "Ready for Dev"
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            Order = 2,
                            Status = 2,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 1,
                            Order = 3,
                            Status = 3,
                            Title = "In Review"
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 1,
                            Order = 4,
                            Status = 4,
                            Title = "Done"
                        });
                });

            modelBuilder.Entity("AIDevBuddy.Data.LlmSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalModelPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LlmSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = false,
                            IsEnabled = false,
                            ModelName = "gpt-4o",
                            Provider = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Endpoint = "https://open.bigmodel.cn/api/paas/v4/",
                            IsDefault = false,
                            IsEnabled = false,
                            ModelName = "glm-4",
                            Provider = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Endpoint = "https://api.anthropic.com/v1/",
                            IsDefault = false,
                            IsEnabled = false,
                            ModelName = "claude-sonnet-4-6",
                            Provider = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Endpoint = "http://localhost:11434/api/",
                            IsDefault = false,
                            IsEnabled = false,
                            ModelName = "llama3",
                            Provider = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AIDevBuddy.Data.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BmadPhase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeadAgentId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AIDevBuddy.Data.ProjectAgentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAgentAssignments");
                });

            modelBuilder.Entity("AIDevBuddy.Data.AgentMessage", b =>
                {
                    b.HasOne("AIDevBuddy.Data.Project", "Project")
                        .WithMany("Messages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDevBuddy.Data.Agent", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDevBuddy.Data.Agent", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AIDevBuddy.Data.BmadMemory", b =>
                {
                    b.HasOne("AIDevBuddy.Data.Project", "Project")
                        .WithMany("Memories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanCard", b =>
                {
                    b.HasOne("AIDevBuddy.Data.Agent", "AssignedAgent")
                        .WithMany("AssignedCards")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDevBuddy.Data.KanbanColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIDevBuddy.Data.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAgent");

                    b.Navigation("Column");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanColumn", b =>
                {
                    b.HasOne("AIDevBuddy.Data.KanbanBoard", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("AIDevBuddy.Data.Project", b =>
                {
                    b.HasOne("AIDevBuddy.Data.Agent", "LeadAgent")
                        .WithMany()
                        .HasForeignKey("LeadAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LeadAgent");
                });

            modelBuilder.Entity("AIDevBuddy.Data.ProjectAgentAssignment", b =>
                {
                    b.HasOne("AIDevBuddy.Data.Agent", "Agent")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIDevBuddy.Data.Project", "Project")
                        .WithMany("AgentAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDevBuddy.Data.Agent", b =>
                {
                    b.Navigation("AssignedCards");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanBoard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("AIDevBuddy.Data.KanbanColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("AIDevBuddy.Data.Project", b =>
                {
                    b.Navigation("AgentAssignments");

                    b.Navigation("Memories");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
